name: main

on:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
  GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with: 
          node-version: 14.x
      - name: Prepare Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prepare Node
        uses: actions/setup-node@v2
        with: 
          node-version: 14.x
      - name: Prepare Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            .cache/
            public/
            node_modules/
          key: ${{ runner.os }}-build-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Prepare Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
  deploy-union:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: union
      url: https://union-startupresourcecenter.web.app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Package
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - name: Deploy
        uses: joinflux/firebase-action@master
        with:
          args: deploy --only hosting:union
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-union
    environment:
      name: stage
      url: https://stage-startupresource-center.web.app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Package
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - name: Deploy
        uses: joinflux/firebase-action@master
        with:
          args: hosting:stage
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment:
      name: production
      url: https://startupresource.center
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Package
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - name: Deploy
        uses: joinflux/firebase-action@master
        with:
          args: deploy --only hosting:production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
