name: staging

on:
  push:
    branches:
      - staging

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: wake up ghost
        run: curl -I ${{ secrets.GHOST_ADMIN_API_URL }}/ghost/
      - name: Repository Dispatch Build - Staging
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GHA_TOKEN }}
          event-type: build
          client-payload: '{"ref": "${{ github.ref }}", "url": "staging.${{ secrets.DEPLOY_HOST }}"}'
